#!/bin/sh
set -e

## usage
# Simply display the builder usage.  Though it would be nice if some of this
# information was pushed down into the sub-commands.
usage()
{
cat<<EOF
usage: ${0##*/} [options] <command> [command-opts] [all|<package> ...]

Options
-------
 -t, --target	Specify a build-target.  This is a generic concept which tells
		builder the name of the config rule to pick up from the
		.builder/ path at the top of the build-tree.  The global config
		.builder/default is always evaluated before evaluating any
		target-specific configs.  This allows for nightly and release
		targets, as well as architecture specific variations.

 -v, --version	Display the builder version.

 -d, --debug	Enable debug logging.

 -h, --help	Display the builder help and exit (may appear anywhere on the
		command line).

Commands
--------

  query		The query is used internally by builder, while allowing
		one to query various packages from the builder repository.

		options
		-------

		  -b, --build-deps
		  -d, --depends
		  -n, --name
		  -d, --description
		  -v, --version
		  -u, --source-uri
		  -s, --summary

  sync		Fetch , unpack, and patch any sources from the source uri.  If
		a local source has been checked out into the package directory
		then the fetch/unpack portion simply copies the local checked
		out source to the workdir for compilation.

  compile	Compile the source code.  During this stage the CC, CHOST, LD,
		and a variety of other target-specific variables will be set
		and usable within the build rules script. The predefined
		behavior for this action is to cd into the workdir, produce a
		configure script from the configure.in if necessary, run the
		configure with predefined CONFIG_OPTS, and then perform
		a make with MAKE_OPTS.

  archive	Perform a 'make install' of the package into the package's
		sysroot and then produce an archive of the package and store
		that in the build-tree's artifact directory.

  install	Install a package into the build-tree's sysroot (as opposed to
		a packages sysroot or into the build-host's root).  This is
		done automatically for any build-dependent packages.

EOF
}

## cleanup
# deal with temporary junk when we exit
cleanup()
{
	[ -f "${BUILDER_MAKEFILE}" ] && rm -f "${BUILDER_MAKEFILE}"
}

## error <message>
# displays the supplied <message> on stderr
error()
{
	echo "error: $*" >&2
}

## die <message>
# display the supplied <message> and exit with an error
die()
{
	error "$*"
	exit 1
}

## import <package>
# import a package into the current program space
import()
{
	# Evaluate our environment data
	# There is a bit of a performance penalty here in that the query
	# routine will source the build-rules to finish collecting data, so we
	# end up sourcing the Buildrules twice.
	eval $(build query -E "${1}")

	# Source in the category Buildrules
	if [ -f "${BUILDER_PKGDIR}/${CATEGORY}/.buildrules" ]; then
		. "${BUILDER_PKGDIR}/${CATEGORY}/.buildrules"
	fi

	# Source in the package Buildrules
	. "${RULESFILE}"

	if [ "${CATEGORY}/${NAME}" != "${1}" ]; then
		die "Buildrules can not set the package name"
	fi

	if [ -z "${VERSION}" ]; then
		die "missing version in '${NAME}'"
	fi

	if [ -z "${DESCRIPTION}" ]; then
		die "missing description in '${NAME}'"
	fi

	if [ -z "${SOURCE_URI}" ]; then
		die "SOURCE_URI undefined and no source directory in '${CATEGORY}/${NAME}'"
	fi
}

if [ ! -z "${BUILDER_DEBUG}" ]; then
	set -x
fi

##
# Check to see if we are wrapping a sub-command
# FIXME support custom commands
BUILD_COMMAND=
if [ -f "${1}" ]; then
	case "${1}" in
	(*build-*)
		BUILD_COMMAND="${1}"
		shift
		. "${BUILD_COMMAND}"
		# exit with the exit status of the last command from within the
		# sub-script.  This is normal shell behavior, we are just
		# making it explicit.
		exit $?
		;;
	esac
fi

for arg in "$@"; do
	case "${arg}" in
	(-h|-help|--help)	usage; exit 0;;
	esac
done
unset arg

DEBUG="0"
while [ "$#" -gt "0" ]; do
	case "$1" in
	(-v|-version|--version)	version; exit 0;;
	(-t|-target|--target)
		shift 1
		if [ "$#" -eq "0" ]; then
			echo "error: no target specified" >&2
			exit 1
		fi
		BUILDER_TARGET="${1}"
		shift 1
		;;
	(-d|-debug|--debug)
		BUILDER_DEBUG=1
		export BUILDER_DEBUG
		set -x
		;;
	(-*)	echo "error: unknown option '${1}'" >&2
		echo "try '${0} --help'" >&2
		exit 1
		;;
	(*)	break
		;;
	esac
	shift 1
	echo "$@"
done

##
# Done with arguments, time for setting up the enviroment for the build
BUILDER_TOPDIR="${PWD}"
while [ ! -z "${BUILDER_TOPDIR}" ]; do
	[ -d "${BUILDER_TOPDIR}/.builder" ] && break
	BUILDER_TOPDIR="${BUILDER_TOPDIR%/*}"
done
if [ -z "${BUILDER_TOPDIR}" ]; then
	echo "error: current path not in a build-tree" >&2
	exit 1
fi

##
# This may be a little bit confusing to most.  The core issue here is the
# ability to deal with compiled-in defaults, user-defined defaults, environment
# settings, and target settings.
CFGDIR="${BUILDER_TOPDIR}/.builder"

# grab the default and target settings if available, let the target settings
# override the user-defined defaults.
TARGET="default"
if [ -f "${CFGDIR}/${TARGET}" ]; then
	. "${CFGDIR}/${TARGET}"
fi
CFGDIR="${BUILDER_TOPDIR}/.builder"
TARGET="${BUILDER_TARGET:-${TARGET}}"
if [ "${TARGET}" != "default" ]; then
	if [ ! -f "${CFGDIR}/${TARGET}" ]; then
		echo "error: invalid target '${TARGET}'" >&2
		exit 1
	fi
	. "${CFGDIR}/${TARGET}"
fi
export TARGET

# Available to be set in the target
PROJECT_NAME="${PROJECT_NAME:-platform}"
ARCHIVE_FORMAT="${ARCHIVE_FORMAT:-tar.bz2}"
export PROJECT_NAME ARCHIVE_FORMAT

# FIXME this stuff needs to be detected in a more reliable fashion
ARCH="${ARCH:-$(uname -m)}"
VENDOR="${VENDOR:-pc}"
PLATFORM="${PLATFORM:-$(uname -i|tr '[A-Z]' '[a-z]')}"
export ARCH VENDOR PLATFORM

# FIXME We should be defaulting to the build platform for this data if the
# target platform is unspecified
CHOST="${ARCH}-${VENDOR}-${PLATFORM}"
if [ ! -z "${LIBC}" ]; then
	export LIBC
	CHOST="${CHOST}-${LIBC}"
fi
export CHOST

# If the MAKE_OPTS are not set then find the number of CPU's and set them.
if [ -z "${MAKE_OPTS}" ]; then
	NUM_CPUS="$(awk '/^processor/{print$3}'< /proc/cpuinfo|sort|uniq|tail -n 1)"
	NUM_CPUS="$((${NUM_CPUS} + 1))"
	MAKE_OPTS="-j$((${NUM_CPUS} + 1))"
fi
export MAKE_OPTS

# set the builtin defaults based on the BUILDER_TOPDIR
BUILDER_PKGDIR="${BUILDER_TOPDIR}/packages"
BUILDER_SRCDIR="${BUILDER_TOPDIR}/sources"
BUILDER_ATFDIR="${BUILDER_TOPDIR}/artifacts"
BUILDER_TMPDIR="${BUILDER_TOPDIR}/tmp"
BUILDER_LIBDIR="${BUILDER_TOPDIR}/scripts/builder"

export BUILDER_CFGDIR BUILDER_PKGDIR BUILDER_SRCDIR
export BUILDER_ATFDIR BUILDER_LIBDIR BUILDER_TOPDIR
export BUILDER_TMPDIR

# Installation locations for the cross-tools and the target-root
SYSROOT="${SYSROOT:-${BUILDER_TOPDIR}/sysroot}"
export SYSROOT

PATH="${BUILDER_LIBDIR}:${PATH}"
export PATH

# if we aren't given an action then we do everything
ACTION="archive"
if [ "$#" -gt "0" ]; then
	ACTION="${1}"
	shift 1
fi

# FIXME Support custom commands somehow..
if [ ! -x "${BUILDER_LIBDIR}/build-${ACTION}" ]; then
	error "unknown action '${ACTION}'"
	echo "try '${0} --help'" >&2
	exit 1
fi

# info is a special case
# FIXME this is semi-busted
if [ "${ACTION}" = "query" ]; then
	exec "${BUILDER_LIBDIR}/build-query" "${@}"
fi

if [ "$#" -lt "1" ]; then
	NAME="all"
	if [ "${PWD##${BUILDER_PKGDIR}/}" != "${PWD}" ]; then
		name1="${PWD##${BUILDER_PKGDIR}/}"
		if [ "${name1}" = "${name#*/*/}" ]; then
			NAME="${name1}"
		else
			name2="${name1#*/*/}"
			NAME="${name1%/${name2}}"
		fi
	fi
	set -- "${NAME}"
fi

if [ "${1}" != "all" ]; then
	# sort/uniq the argument list
	set -- $(for package in "$@"; do echo "${package}" ; done | sort | uniq)
	for package in "$@"; do
		# If all is specified anywhere in the argument list than just discard
		# everything else.
		if [ "${package}" = "all" ]; then
			exec "${0}" "${ACTION}" "${package}"
		fi
		if ! build-query --exists "${package}"; then
			exit 1
		fi
	done
fi

# build the Makefile
trap cleanup EXIT
BUILDER_MAKEFILE="$(mktemp ${BUILDER_TMPDIR}/builder_makefile.XXXXXXXX)"
if [ ! -f "${BUILDER_MAKEFILE}" ]; then
	die "failed to generate build dependencies"
fi
export BUILDER_MAKEFILE
"${BUILDER_LIBDIR}/build-makedeps" || die "failed generate build dependencies"

packages=
for package in "$@"; do
	if [ "${package}" != "all" ]; then
		package="$(build query --pkgname "${package}")"
	fi
	package="$(echo "${package}"|tr '/-' '__')"
	packages="${packages} ${package}_${ACTION}"
done
set -- ${packages}
unset packages

# exec out to make with the appropriate Makefile
make ${MAKE_OPTS} -r -f "${BUILDER_MAKEFILE}" "${@}"
